// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../../core/resource';
import * as TerritoriesAPI from './territories';
import {
  Account,
  AccountBranding,
  AccountPortal,
  AccountUser,
  Address,
  Attribute,
  Consumption,
  CreateTerritoryRequest,
  Department,
  Geolocation,
  Item,
  ItemCategory,
  ListAttribute,
  ListConsumption,
  ListLocation,
  ListMachine,
  ListProductionStep,
  ListProperty,
  ListScanningStation,
  ListTerritory,
  ListUnitGroupUnit,
  Location,
  Machine,
  Owner,
  PageInfo,
  ProductLine,
  ProductionOutput,
  ProductionStep,
  Property,
  Quantity,
  Rate,
  Role,
  ScanningStation,
  Territories,
  Territory,
  TerritoryCreateParams,
  TerritoryDeleteParams,
  TerritoryDeleteResponse,
  TerritoryListParams,
  TerritoryRetrieveParams,
  TerritoryUpdateParams,
  Unit,
  UnitGroup,
  UnitGroupUnit,
  UpdateTerritoryRequest,
} from './territories';

export class Accounts extends APIResource {
  territories: TerritoriesAPI.Territories = new TerritoriesAPI.Territories(this._client);
}

Accounts.Territories = Territories;

export declare namespace Accounts {
  export {
    Territories as Territories,
    type Account as Account,
    type AccountBranding as AccountBranding,
    type AccountPortal as AccountPortal,
    type AccountUser as AccountUser,
    type Address as Address,
    type Attribute as Attribute,
    type Consumption as Consumption,
    type CreateTerritoryRequest as CreateTerritoryRequest,
    type Department as Department,
    type Geolocation as Geolocation,
    type Item as Item,
    type ItemCategory as ItemCategory,
    type ListAttribute as ListAttribute,
    type ListConsumption as ListConsumption,
    type ListLocation as ListLocation,
    type ListMachine as ListMachine,
    type ListProductionStep as ListProductionStep,
    type ListProperty as ListProperty,
    type ListScanningStation as ListScanningStation,
    type ListTerritory as ListTerritory,
    type ListUnitGroupUnit as ListUnitGroupUnit,
    type Location as Location,
    type Machine as Machine,
    type Owner as Owner,
    type PageInfo as PageInfo,
    type ProductLine as ProductLine,
    type ProductionOutput as ProductionOutput,
    type ProductionStep as ProductionStep,
    type Property as Property,
    type Quantity as Quantity,
    type Rate as Rate,
    type Role as Role,
    type ScanningStation as ScanningStation,
    type Territory as Territory,
    type Unit as Unit,
    type UnitGroup as UnitGroup,
    type UnitGroupUnit as UnitGroupUnit,
    type UpdateTerritoryRequest as UpdateTerritoryRequest,
    type TerritoryDeleteResponse as TerritoryDeleteResponse,
    type TerritoryCreateParams as TerritoryCreateParams,
    type TerritoryRetrieveParams as TerritoryRetrieveParams,
    type TerritoryUpdateParams as TerritoryUpdateParams,
    type TerritoryListParams as TerritoryListParams,
    type TerritoryDeleteParams as TerritoryDeleteParams,
  };
}
