// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../../core/resource';
import * as AccountGroupsAPI from './account-groups';
import {
  Account,
  AccountBranding,
  AccountGroup,
  AccountGroupCreateParams,
  AccountGroupDeleteResponse,
  AccountGroupListParams,
  AccountGroupProductLineAccess,
  AccountGroupUpdateParams,
  AccountGroups,
  AccountPortal,
  Address,
  CreateAccountGroupProductLineAccessRequest,
  Geolocation,
  ListAccountGroupProductLineAccess,
  ListProductLine,
  ListUnitGroupUnit,
  Owner,
  PageInfo,
  ProductLine,
  Unit,
  UnitGroup,
  UnitGroupUnit,
  UpdateAccountGroupProductLineAccessRequest,
} from './account-groups';
import * as CustomersAPI from './customers';
import {
  Account as CustomersAPIAccount,
  AccountBranding as CustomersAPIAccountBranding,
  AccountGroup as CustomersAPIAccountGroup,
  AccountPortal as CustomersAPIAccountPortal,
  AccountUser,
  Address as CustomersAPIAddress,
  Attribute,
  Carrier,
  Consumption,
  CreateCustomerProductLineAccessRequest,
  Customer,
  CustomerContactInfo,
  CustomerCreateParams,
  CustomerDefaults,
  CustomerDeleteResponse,
  CustomerFreightPreferences,
  CustomerListParams,
  CustomerNotificationPreferences,
  CustomerProductLineAccess,
  CustomerUpdateParams,
  Customers,
  Department,
  Geolocation as CustomersAPIGeolocation,
  Item,
  ItemCategory,
  ListAccountGroup,
  ListAttribute,
  ListConsumption,
  ListCustomer,
  ListCustomerProductLineAccess,
  ListLocation,
  ListMachine,
  ListProductLine as CustomersAPIListProductLine,
  ListProductionStep,
  ListProperty,
  ListScanningStation,
  ListServiceLevel,
  ListUnitGroupUnit as CustomersAPIListUnitGroupUnit,
  Location,
  Machine,
  Owner as CustomersAPIOwner,
  PageInfo as CustomersAPIPageInfo,
  PaymentTerm,
  Priority,
  ProductLine as CustomersAPIProductLine,
  ProductionOutput,
  ProductionStep,
  Property,
  Quantity,
  Rate,
  Role,
  ScanningStation,
  ServiceLevel,
  ShippingTerm,
  Unit as CustomersAPIUnit,
  UnitGroup as CustomersAPIUnitGroup,
  UnitGroupUnit as CustomersAPIUnitGroupUnit,
  UpdateCustomerProductLineAccessRequest,
} from './customers';

export class ProductLineAccess extends APIResource {
  accountGroups: AccountGroupsAPI.AccountGroups = new AccountGroupsAPI.AccountGroups(this._client);
  customers: CustomersAPI.Customers = new CustomersAPI.Customers(this._client);
}

ProductLineAccess.AccountGroups = AccountGroups;
ProductLineAccess.Customers = Customers;

export declare namespace ProductLineAccess {
  export {
    AccountGroups as AccountGroups,
    type Account as Account,
    type AccountBranding as AccountBranding,
    type AccountGroup as AccountGroup,
    type AccountGroupProductLineAccess as AccountGroupProductLineAccess,
    type AccountPortal as AccountPortal,
    type Address as Address,
    type CreateAccountGroupProductLineAccessRequest as CreateAccountGroupProductLineAccessRequest,
    type Geolocation as Geolocation,
    type ListAccountGroupProductLineAccess as ListAccountGroupProductLineAccess,
    type ListProductLine as ListProductLine,
    type ListUnitGroupUnit as ListUnitGroupUnit,
    type Owner as Owner,
    type PageInfo as PageInfo,
    type ProductLine as ProductLine,
    type Unit as Unit,
    type UnitGroup as UnitGroup,
    type UnitGroupUnit as UnitGroupUnit,
    type UpdateAccountGroupProductLineAccessRequest as UpdateAccountGroupProductLineAccessRequest,
    type AccountGroupDeleteResponse as AccountGroupDeleteResponse,
    type AccountGroupCreateParams as AccountGroupCreateParams,
    type AccountGroupUpdateParams as AccountGroupUpdateParams,
    type AccountGroupListParams as AccountGroupListParams,
  };

  export {
    Customers as Customers,
    type CustomersAPIAccount as Account,
    type CustomersAPIAccountBranding as AccountBranding,
    type CustomersAPIAccountGroup as AccountGroup,
    type CustomersAPIAccountPortal as AccountPortal,
    type AccountUser as AccountUser,
    type CustomersAPIAddress as Address,
    type Attribute as Attribute,
    type Carrier as Carrier,
    type Consumption as Consumption,
    type CreateCustomerProductLineAccessRequest as CreateCustomerProductLineAccessRequest,
    type Customer as Customer,
    type CustomerContactInfo as CustomerContactInfo,
    type CustomerDefaults as CustomerDefaults,
    type CustomerFreightPreferences as CustomerFreightPreferences,
    type CustomerNotificationPreferences as CustomerNotificationPreferences,
    type CustomerProductLineAccess as CustomerProductLineAccess,
    type Department as Department,
    type CustomersAPIGeolocation as Geolocation,
    type Item as Item,
    type ItemCategory as ItemCategory,
    type ListAccountGroup as ListAccountGroup,
    type ListAttribute as ListAttribute,
    type ListConsumption as ListConsumption,
    type ListCustomer as ListCustomer,
    type ListCustomerProductLineAccess as ListCustomerProductLineAccess,
    type ListLocation as ListLocation,
    type ListMachine as ListMachine,
    type CustomersAPIListProductLine as ListProductLine,
    type ListProductionStep as ListProductionStep,
    type ListProperty as ListProperty,
    type ListScanningStation as ListScanningStation,
    type ListServiceLevel as ListServiceLevel,
    type CustomersAPIListUnitGroupUnit as ListUnitGroupUnit,
    type Location as Location,
    type Machine as Machine,
    type CustomersAPIOwner as Owner,
    type CustomersAPIPageInfo as PageInfo,
    type PaymentTerm as PaymentTerm,
    type Priority as Priority,
    type CustomersAPIProductLine as ProductLine,
    type ProductionOutput as ProductionOutput,
    type ProductionStep as ProductionStep,
    type Property as Property,
    type Quantity as Quantity,
    type Rate as Rate,
    type Role as Role,
    type ScanningStation as ScanningStation,
    type ServiceLevel as ServiceLevel,
    type ShippingTerm as ShippingTerm,
    type CustomersAPIUnit as Unit,
    type CustomersAPIUnitGroup as UnitGroup,
    type CustomersAPIUnitGroupUnit as UnitGroupUnit,
    type UpdateCustomerProductLineAccessRequest as UpdateCustomerProductLineAccessRequest,
    type CustomerDeleteResponse as CustomerDeleteResponse,
    type CustomerCreateParams as CustomerCreateParams,
    type CustomerUpdateParams as CustomerUpdateParams,
    type CustomerListParams as CustomerListParams,
  };
}
