/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health Check
         * @description Returns the current health status of the API.
         */
        get: operations["get-health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/access-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Refresh Token
         * @description This endpoint is utilized to refresh an access token using a refresh token.
         *     Once completed, a new access token is set in a cookie.
         */
        put: operations["refresh-token"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/actions/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login User
         * @description This endpoint is utilized to login a user. Once completed, the user object is
         *     returned, and an access and refresh token are set in cookies.
         */
        post: operations["login-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/passwords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Password
         * @description This endpoint is utilized to create a new password for a user. Once completed, new cookies
         *     are set in cookies.
         */
        post: operations["create-new-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/passwords/actions/request-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description This endpoint is utilized to request a password reset for a user. An email will be sent to the user
         *     with a link to reset their password.
         */
        post: operations["request-password-reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/passwords/actions/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description This endpoint is utilized to reset a user's password using a password reset token.
         *     Once completed, new access and refresh tokens are set in cookies.
         */
        post: operations["reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Refresh Token
         * @description This endpoint is utilized to revoke a refresh token.
         *     Once completed, the refresh token is revoked and is no longer valid for refreshing an access token.
         */
        delete: operations["revoke-refresh-token"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description This endpoint is utilized to register a new user on the customer portal. Once completed, the user object is
         *     returned, and an access and refresh token are set in cookies.
         */
        post: operations["register-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description APIErrorResponse is the top-level envelope wrapping a ResponseError.
         *     All API error responses use this shape: { "error": { ... } }.
         * @example {
         *       "error": {
         *         "code": "validation_failed",
         *         "doc_url": "https://docs.augno.com/errors/validation_failed",
         *         "is_transient": false,
         *         "message": "The request was invalid.",
         *         "param": "email",
         *         "type": "invalid_request_error"
         *       }
         *     }
         */
        APIErrorResponse: {
            /** @description The error object containing details about what went wrong. */
            error: components["schemas"]["ResponseError"];
        };
        /**
         * @description Healthcheck contains information on the health of the application.
         * @example {
         *       "status": "healthy"
         *     }
         */
        Healthcheck: {
            /** @description Current operational status of the API service */
            status: string;
        };
        /**
         * @description The request to login a user
         * @example {
         *       "identifier": "jdoe",
         *       "password": "super-secret-password"
         *     }
         */
        LoginRequest: {
            /** @description The username or email for authentication */
            identifier: string;
            /** @description The password of the user */
            password: string;
        };
        /**
         * @description The request to register a new user
         * @example {
         *       "email": "jdoe@augno.com",
         *       "name": "John Doe",
         *       "password": "super-secret-password"
         *     }
         */
        RegisterRequest: {
            /** @description The email address for the new user */
            email: string;
            /** @description The full name of the new user */
            name: string;
            /** @description The password for the new user */
            password: string;
        };
        /**
         * @description The request to request a password reset
         * @example {
         *       "identifier": "jdoe@augno.com"
         *     }
         */
        RequestPasswordResetRequest: {
            /** @description The account slug (optional) */
            account_slug?: string | null;
            /** @description The username or email of the account to reset */
            identifier: string;
        };
        /**
         * @description The request to reset a user's password
         * @example {
         *       "password": "new-super-secret-password",
         *       "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1Z25vLmNvbSIsInN1YiI6InVzXzAxZ2Y3YTgyMDBlMXNyMjBwZzl3eDZkMmswIiwiZXhwIjoxNzU2ODIzMzI5LCJpYXQiOjE3NTY4MTk3Mjl9.2ZodhtiHDqIQnDjzrJZvqIdEbQbmkgbTaz4OXdbXCWNjzEsy2-5e78XQRu-aZ8MoZ2dusIVKQcN1Tm-arKR0_Q"
         *     }
         */
        ResetPasswordRequest: {
            /** @description The new password of the user */
            password: string;
            /** @description The password reset token */
            token: string;
        };
        /**
         * @description ResponseError is the JSON-serializable error body returned to API clients. It contains
         *     only public information. This struct is used by the OpenAPI schema generator to produce
         *     documentation.
         * @example {
         *       "code": "validation_failed",
         *       "doc_url": "https://docs.augno.com/errors/validation_failed",
         *       "is_transient": false,
         *       "message": "The request was invalid.",
         *       "param": "email",
         *       "type": "invalid_request_error"
         *     }
         */
        ResponseError: {
            /** @description A machine-readable code for the error. */
            code: string;
            /** @description A URL to documentation about the error. */
            doc_url: string | null;
            /** @description Whether this error is transient and the request can be retried. */
            is_transient: boolean;
            /** @description A human-readable message providing more details about the error. */
            message: string;
            /** @description The parameter that caused the error, if applicable. */
            param: string | null;
            /** @description The type of error. */
            type: string;
        };
        /**
         * @description The request to update a user's password
         * @example {
         *       "new_password": "new-super-secret-password",
         *       "old_password": "super-secret-password"
         *     }
         */
        UpdatePasswordRequest: {
            /** @description The new password to be set */
            new_password: string;
            /** @description The user's current password */
            old_password: string;
        };
        /**
         * @description A user in the Augno system
         * @example {
         *       "created_at": "2026-05-10T00:00:00Z",
         *       "email": "jdoe@augno.com",
         *       "email_verified": "2026-05-10T01:00:00Z",
         *       "id": "us_01gf7a8200e9pvbd6bgyq395ae",
         *       "image_url": "https://example.com/avatar.jpg",
         *       "name": "John Doe",
         *       "object": "user",
         *       "updated_at": "2026-05-10T00:23:00Z",
         *       "username": "jdoe"
         *     }
         */
        User: {
            /**
             * Format: date-time
             * @description When this user was created
             */
            created_at: string;
            /** @description The user's email address */
            email: string | null;
            /**
             * Format: date-time
             * @description When the user's email was verified, null if unverified
             */
            email_verified: string | null;
            /** @description The unique identifier for this user */
            id: string;
            /** @description URL to the user's profile image */
            image_url: string | null;
            /** @description The user's display name */
            name: string | null;
            /**
             * @description The resource type identifier
             * @enum {string}
             */
            object: "user";
            /**
             * Format: date-time
             * @description When this user was last updated
             */
            updated_at: string;
            /** @description The user's unique username */
            username: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response for Get Health Check */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "healthy"
                     *     }
                     */
                    "application/json": components["schemas"]["Healthcheck"];
                };
            };
            /** @description Bad Request response for Get Health Check */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Get Health Check */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Get Health Check */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Get Health Check */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Get Health Check */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Get Health Check */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Get Health Check */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                /** @description The Secure refresh token cookie for Refresh Token */
                "__Secure-augno.refresh-token": string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful response for Refresh Token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            /** @description Bad Request response for Refresh Token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Refresh Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Refresh Token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Refresh Token */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Refresh Token */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Refresh Token */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Refresh Token */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "login-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for Login User */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "identifier": "jdoe",
                 *       "password": "super-secret-password"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful response for Login User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "created_at": "2026-05-10T00:00:00Z",
                     *       "email": "jdoe@augno.com",
                     *       "email_verified": "2026-05-10T01:00:00Z",
                     *       "id": "us_01gf7a8200e9pvbd6bgyq395ae",
                     *       "image_url": "https://example.com/avatar.jpg",
                     *       "name": "John Doe",
                     *       "object": "user",
                     *       "updated_at": "2026-05-10T00:23:00Z",
                     *       "username": "jdoe"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad Request response for Login User */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Login User */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Login User */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Login User */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Login User */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Login User */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Login User */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "create-new-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for Create New Password */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "new_password": "new-super-secret-password",
                 *       "old_password": "super-secret-password"
                 *     }
                 */
                "application/json": components["schemas"]["UpdatePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful response for Create New Password */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            /** @description Bad Request response for Create New Password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Create New Password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Create New Password */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Create New Password */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Create New Password */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Create New Password */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Create New Password */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for Request Password Reset */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "identifier": "jdoe@augno.com"
                 *     }
                 */
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful response for Request Password Reset */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            /** @description Bad Request response for Request Password Reset */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Request Password Reset */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Request Password Reset */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Request Password Reset */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Request Password Reset */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Request Password Reset */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Request Password Reset */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for Reset Password */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "password": "new-super-secret-password",
                 *       "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1Z25vLmNvbSIsInN1YiI6InVzXzAxZ2Y3YTgyMDBlMXNyMjBwZzl3eDZkMmswIiwiZXhwIjoxNzU2ODIzMzI5LCJpYXQiOjE3NTY4MTk3Mjl9.2ZodhtiHDqIQnDjzrJZvqIdEbQbmkgbTaz4OXdbXCWNjzEsy2-5e78XQRu-aZ8MoZ2dusIVKQcN1Tm-arKR0_Q"
                 *     }
                 */
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful response for Reset Password */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            /** @description Bad Request response for Reset Password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Reset Password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Reset Password */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Reset Password */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Reset Password */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Reset Password */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Reset Password */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "revoke-refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                /** @description The Secure refresh token cookie for Revoke Refresh Token */
                "__Secure-augno.refresh-token": string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful response for Revoke Refresh Token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            /** @description Bad Request response for Revoke Refresh Token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Revoke Refresh Token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Revoke Refresh Token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Revoke Refresh Token */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Revoke Refresh Token */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Revoke Refresh Token */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Revoke Refresh Token */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
    "register-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The request body for Register User */
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "email": "jdoe@augno.com",
                 *       "name": "John Doe",
                 *       "password": "super-secret-password"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful response for Register User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "created_at": "2026-05-10T00:00:00Z",
                     *       "email": "jdoe@augno.com",
                     *       "email_verified": "2026-05-10T01:00:00Z",
                     *       "id": "us_01gf7a8200e9pvbd6bgyq395ae",
                     *       "image_url": "https://example.com/avatar.jpg",
                     *       "name": "John Doe",
                     *       "object": "user",
                     *       "updated_at": "2026-05-10T00:23:00Z",
                     *       "username": "jdoe"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Bad Request response for Register User */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Unauthorized response for Register User */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Forbidden response for Register User */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Not Found response for Register User */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Conflict response for Register User */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Too Many Requests response for Register User */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
            /** @description Internal Server Error response for Register User */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "validation_failed",
                     *         "doc_url": "https://docs.augno.com/errors/validation_failed",
                     *         "is_transient": false,
                     *         "message": "The request was invalid.",
                     *         "param": "email",
                     *         "type": "invalid_request_error"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrorResponse"];
                };
            };
        };
    };
}
