// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as ProductLinesAPI from './product-lines';
import {
  Account,
  AccountBranding,
  AccountPortal,
  Address,
  CreateProductLineRequest,
  Geolocation,
  ListProductLine,
  ListUnitGroupUnit,
  Owner,
  PageInfo,
  ProductLine,
  ProductLineCreateParams,
  ProductLineDeleteResponse,
  ProductLineListParams,
  ProductLineRetrieveParams,
  ProductLineUpdateParams,
  ProductLines,
  Unit,
  UnitGroup,
  UnitGroupUnit,
  UpdateProductLineRequest,
} from './product-lines';
import * as ProductTypesAPI from './product-types';
import {
  CreateProductTypeRequest,
  ListProductType,
  PageInfo as ProductTypesAPIPageInfo,
  ProductType,
  ProductTypeCreateParams,
  ProductTypeDeleteResponse,
  ProductTypeListParams,
  ProductTypeUpdateParams,
  ProductTypes,
  UpdateProductTypeRequest,
} from './product-types';
import * as CatalogAPI from './catalog_/catalog_';
import { Catalog as CatalogAPICatalog } from './catalog_/catalog_';
import * as ItemCategoriesAPI from './item-categories/item-categories';
import {
  Account as ItemCategoriesAPIAccount,
  AccountBranding as ItemCategoriesAPIAccountBranding,
  AccountPortal as ItemCategoriesAPIAccountPortal,
  Address as ItemCategoriesAPIAddress,
  Attribute,
  CreateItemCategoryRequest,
  Geolocation as ItemCategoriesAPIGeolocation,
  ItemCategories,
  ItemCategory,
  ItemCategoryChangeUnitGroupParams,
  ItemCategoryChangeUnitGroupResponse,
  ItemCategoryCreateParams,
  ItemCategoryDeleteResponse,
  ItemCategoryListParams,
  ItemCategoryRetrieveParams,
  ItemCategoryUpdateParams,
  ListAttribute,
  ListItemCategory,
  ListProperty,
  ListUnitGroupUnit as ItemCategoriesAPIListUnitGroupUnit,
  Owner as ItemCategoriesAPIOwner,
  PageInfo as ItemCategoriesAPIPageInfo,
  Property,
  Unit as ItemCategoriesAPIUnit,
  UnitGroup as ItemCategoriesAPIUnitGroup,
  UnitGroupUnit as ItemCategoriesAPIUnitGroupUnit,
  UpdateItemCategoryRequest,
} from './item-categories/item-categories';
import * as ItemsAPI from './items/items';
import {
  Account as ItemsAPIAccount,
  AccountBranding as ItemsAPIAccountBranding,
  AccountPortal as ItemsAPIAccountPortal,
  Address as ItemsAPIAddress,
  Attribute as ItemsAPIAttribute,
  Geolocation as ItemsAPIGeolocation,
  Item,
  ItemCategory as ItemsAPIItemCategory,
  ItemChangeCategoryParams,
  ItemCosts,
  ItemListParams,
  ItemRetrieveParams,
  ItemRetrieveTrendsParams,
  ItemTrendPoint,
  ItemTrends,
  Items,
  ListAttribute as ItemsAPIListAttribute,
  ListItem,
  ListItemTrendPoint,
  ListProperty as ItemsAPIListProperty,
  ListUnitGroupUnit as ItemsAPIListUnitGroupUnit,
  Owner as ItemsAPIOwner,
  PageInfo as ItemsAPIPageInfo,
  Property as ItemsAPIProperty,
  Rate,
  Unit as ItemsAPIUnit,
  UnitGroup as ItemsAPIUnitGroup,
  UnitGroupUnit as ItemsAPIUnitGroupUnit,
} from './items/items';
import * as MaterialsAPI from './materials/materials';
import {
  Account as MaterialsAPIAccount,
  AccountBranding as MaterialsAPIAccountBranding,
  AccountPortal as MaterialsAPIAccountPortal,
  Address as MaterialsAPIAddress,
  Attribute as MaterialsAPIAttribute,
  CreateMaterialRequest,
  Geolocation as MaterialsAPIGeolocation,
  Item as MaterialsAPIItem,
  ItemCategory as MaterialsAPIItemCategory,
  ListAttribute as MaterialsAPIListAttribute,
  ListMaterial,
  ListProperty as MaterialsAPIListProperty,
  ListUnitGroupUnit as MaterialsAPIListUnitGroupUnit,
  Material,
  MaterialCreateParams,
  MaterialListParams,
  MaterialRetrieveParams,
  MaterialUpdateParams,
  Materials,
  Owner as MaterialsAPIOwner,
  PageInfo as MaterialsAPIPageInfo,
  Property as MaterialsAPIProperty,
  Quantity,
  QuantityInputRequest,
  Rate as MaterialsAPIRate,
  RateInput,
  Unit as MaterialsAPIUnit,
  UnitGroup as MaterialsAPIUnitGroup,
  UnitGroupUnit as MaterialsAPIUnitGroupUnit,
  UpdateMaterialRequest,
} from './materials/materials';
import * as PartsAPI from './parts/parts';
import {
  Account as PartsAPIAccount,
  AccountBranding as PartsAPIAccountBranding,
  AccountPortal as PartsAPIAccountPortal,
  Address as PartsAPIAddress,
  Attribute as PartsAPIAttribute,
  CreatePartRequest,
  Geolocation as PartsAPIGeolocation,
  Item as PartsAPIItem,
  ItemCategory as PartsAPIItemCategory,
  ListAttribute as PartsAPIListAttribute,
  ListPart,
  ListProperty as PartsAPIListProperty,
  ListUnitGroupUnit as PartsAPIListUnitGroupUnit,
  Owner as PartsAPIOwner,
  PageInfo as PartsAPIPageInfo,
  Part,
  PartCreateParams,
  PartListParams,
  PartRetrieveParams,
  PartUpdateParams,
  Parts,
  Property as PartsAPIProperty,
  Rate as PartsAPIRate,
  RateInput as PartsAPIRateInput,
  Unit as PartsAPIUnit,
  UnitGroup as PartsAPIUnitGroup,
  UnitGroupUnit as PartsAPIUnitGroupUnit,
  UpdatePartRequest,
} from './parts/parts';
import * as ProductsAPI from './products/products';
import {
  Account as ProductsAPIAccount,
  AccountBranding as ProductsAPIAccountBranding,
  AccountPortal as ProductsAPIAccountPortal,
  Address as ProductsAPIAddress,
  Attribute as ProductsAPIAttribute,
  CreateProductRequest,
  Geolocation as ProductsAPIGeolocation,
  Item as ProductsAPIItem,
  ItemCategory as ProductsAPIItemCategory,
  ListAttribute as ProductsAPIListAttribute,
  ListProduct,
  ListProperty as ProductsAPIListProperty,
  ListUnitGroupUnit as ProductsAPIListUnitGroupUnit,
  Owner as ProductsAPIOwner,
  PageInfo as ProductsAPIPageInfo,
  Product,
  ProductChangeProductLineParams,
  ProductCreateParams,
  ProductDeleteParams,
  ProductLine as ProductsAPIProductLine,
  ProductListParams,
  ProductRetrieveParams,
  ProductUpdateParams,
  Products,
  Property as ProductsAPIProperty,
  Rate as ProductsAPIRate,
  RateInput as ProductsAPIRateInput,
  Unit as ProductsAPIUnit,
  UnitGroup as ProductsAPIUnitGroup,
  UnitGroupUnit as ProductsAPIUnitGroupUnit,
  UpdateProductRequest,
} from './products/products';
import * as PropertiesAPI from './properties/properties';
import {
  Attribute as PropertiesAPIAttribute,
  CreatePropertyRequest,
  ListAttribute as PropertiesAPIListAttribute,
  ListProperty as PropertiesAPIListProperty,
  PageInfo as PropertiesAPIPageInfo,
  Properties,
  Property as PropertiesAPIProperty,
  PropertyCreateParams,
  PropertyDeleteResponse,
  PropertyListParams,
  PropertyRetrieveParams,
  PropertyUpdateParams,
  UpdatePropertyRequest,
} from './properties/properties';
import * as UnitGroupsAPI from './unit-groups/unit-groups';
import {
  Account as UnitGroupsAPIAccount,
  AccountBranding as UnitGroupsAPIAccountBranding,
  AccountPortal as UnitGroupsAPIAccountPortal,
  Address as UnitGroupsAPIAddress,
  CreateUnitGroupRequest,
  CreateUnitGroupUnitParam,
  Geolocation as UnitGroupsAPIGeolocation,
  ListUnitGroup,
  ListUnitGroupUnit as UnitGroupsAPIListUnitGroupUnit,
  Owner as UnitGroupsAPIOwner,
  PageInfo as UnitGroupsAPIPageInfo,
  Unit as UnitGroupsAPIUnit,
  UnitGroup as UnitGroupsAPIUnitGroup,
  UnitGroupCreateParams,
  UnitGroupDeleteResponse,
  UnitGroupListParams,
  UnitGroupRetrieveParams,
  UnitGroupUnit as UnitGroupsAPIUnitGroupUnit,
  UnitGroupUpdateParams,
  UnitGroups,
  UpdateUnitGroupRequest,
} from './unit-groups/unit-groups';
import * as UnitsAPI from './units/units';
import {
  Account as UnitsAPIAccount,
  AccountBranding as UnitsAPIAccountBranding,
  AccountPortal as UnitsAPIAccountPortal,
  Address as UnitsAPIAddress,
  CreateUnitRequest,
  Geolocation as UnitsAPIGeolocation,
  ListUnit,
  Owner as UnitsAPIOwner,
  PageInfo as UnitsAPIPageInfo,
  Unit as UnitsAPIUnit,
  UnitCreateParams,
  UnitDeleteResponse,
  UnitListParams,
  UnitRetrieveParams,
  UnitUpdateParams,
  Units,
  UpdateUnitRequest,
} from './units/units';

export class Catalog extends APIResource {
  units: UnitsAPI.Units = new UnitsAPI.Units(this._client);
  unitGroups: UnitGroupsAPI.UnitGroups = new UnitGroupsAPI.UnitGroups(this._client);
  properties: PropertiesAPI.Properties = new PropertiesAPI.Properties(this._client);
  items: ItemsAPI.Items = new ItemsAPI.Items(this._client);
  itemCategories: ItemCategoriesAPI.ItemCategories = new ItemCategoriesAPI.ItemCategories(this._client);
  materials: MaterialsAPI.Materials = new MaterialsAPI.Materials(this._client);
  parts: PartsAPI.Parts = new PartsAPI.Parts(this._client);
  productLines: ProductLinesAPI.ProductLines = new ProductLinesAPI.ProductLines(this._client);
  products: ProductsAPI.Products = new ProductsAPI.Products(this._client);
  productTypes: ProductTypesAPI.ProductTypes = new ProductTypesAPI.ProductTypes(this._client);
  catalog: CatalogAPI.Catalog = new CatalogAPI.Catalog(this._client);
}

Catalog.Units = Units;
Catalog.UnitGroups = UnitGroups;
Catalog.Properties = Properties;
Catalog.Items = Items;
Catalog.ItemCategories = ItemCategories;
Catalog.Materials = Materials;
Catalog.Parts = Parts;
Catalog.ProductLines = ProductLines;
Catalog.Products = Products;
Catalog.ProductTypes = ProductTypes;
Catalog.Catalog = CatalogAPICatalog;

export declare namespace Catalog {
  export {
    Units as Units,
    type UnitsAPIAccount as Account,
    type UnitsAPIAccountBranding as AccountBranding,
    type UnitsAPIAccountPortal as AccountPortal,
    type UnitsAPIAddress as Address,
    type CreateUnitRequest as CreateUnitRequest,
    type UnitsAPIGeolocation as Geolocation,
    type ListUnit as ListUnit,
    type UnitsAPIOwner as Owner,
    type UnitsAPIPageInfo as PageInfo,
    type UnitsAPIUnit as Unit,
    type UpdateUnitRequest as UpdateUnitRequest,
    type UnitDeleteResponse as UnitDeleteResponse,
    type UnitCreateParams as UnitCreateParams,
    type UnitRetrieveParams as UnitRetrieveParams,
    type UnitUpdateParams as UnitUpdateParams,
    type UnitListParams as UnitListParams,
  };

  export {
    UnitGroups as UnitGroups,
    type UnitGroupsAPIAccount as Account,
    type UnitGroupsAPIAccountBranding as AccountBranding,
    type UnitGroupsAPIAccountPortal as AccountPortal,
    type UnitGroupsAPIAddress as Address,
    type CreateUnitGroupRequest as CreateUnitGroupRequest,
    type CreateUnitGroupUnitParam as CreateUnitGroupUnitParam,
    type UnitGroupsAPIGeolocation as Geolocation,
    type ListUnitGroup as ListUnitGroup,
    type UnitGroupsAPIListUnitGroupUnit as ListUnitGroupUnit,
    type UnitGroupsAPIOwner as Owner,
    type UnitGroupsAPIPageInfo as PageInfo,
    type UnitGroupsAPIUnit as Unit,
    type UnitGroupsAPIUnitGroup as UnitGroup,
    type UnitGroupsAPIUnitGroupUnit as UnitGroupUnit,
    type UpdateUnitGroupRequest as UpdateUnitGroupRequest,
    type UnitGroupDeleteResponse as UnitGroupDeleteResponse,
    type UnitGroupCreateParams as UnitGroupCreateParams,
    type UnitGroupRetrieveParams as UnitGroupRetrieveParams,
    type UnitGroupUpdateParams as UnitGroupUpdateParams,
    type UnitGroupListParams as UnitGroupListParams,
  };

  export {
    Properties as Properties,
    type PropertiesAPIAttribute as Attribute,
    type CreatePropertyRequest as CreatePropertyRequest,
    type PropertiesAPIListAttribute as ListAttribute,
    type PropertiesAPIListProperty as ListProperty,
    type PropertiesAPIPageInfo as PageInfo,
    type PropertiesAPIProperty as Property,
    type UpdatePropertyRequest as UpdatePropertyRequest,
    type PropertyDeleteResponse as PropertyDeleteResponse,
    type PropertyCreateParams as PropertyCreateParams,
    type PropertyRetrieveParams as PropertyRetrieveParams,
    type PropertyUpdateParams as PropertyUpdateParams,
    type PropertyListParams as PropertyListParams,
  };

  export {
    Items as Items,
    type ItemsAPIAccount as Account,
    type ItemsAPIAccountBranding as AccountBranding,
    type ItemsAPIAccountPortal as AccountPortal,
    type ItemsAPIAddress as Address,
    type ItemsAPIAttribute as Attribute,
    type ItemsAPIGeolocation as Geolocation,
    type Item as Item,
    type ItemsAPIItemCategory as ItemCategory,
    type ItemCosts as ItemCosts,
    type ItemTrendPoint as ItemTrendPoint,
    type ItemTrends as ItemTrends,
    type ItemsAPIListAttribute as ListAttribute,
    type ListItem as ListItem,
    type ListItemTrendPoint as ListItemTrendPoint,
    type ItemsAPIListProperty as ListProperty,
    type ItemsAPIListUnitGroupUnit as ListUnitGroupUnit,
    type ItemsAPIOwner as Owner,
    type ItemsAPIPageInfo as PageInfo,
    type ItemsAPIProperty as Property,
    type Rate as Rate,
    type ItemsAPIUnit as Unit,
    type ItemsAPIUnitGroup as UnitGroup,
    type ItemsAPIUnitGroupUnit as UnitGroupUnit,
    type ItemRetrieveParams as ItemRetrieveParams,
    type ItemListParams as ItemListParams,
    type ItemChangeCategoryParams as ItemChangeCategoryParams,
    type ItemRetrieveTrendsParams as ItemRetrieveTrendsParams,
  };

  export {
    ItemCategories as ItemCategories,
    type ItemCategoriesAPIAccount as Account,
    type ItemCategoriesAPIAccountBranding as AccountBranding,
    type ItemCategoriesAPIAccountPortal as AccountPortal,
    type ItemCategoriesAPIAddress as Address,
    type Attribute as Attribute,
    type CreateItemCategoryRequest as CreateItemCategoryRequest,
    type ItemCategoriesAPIGeolocation as Geolocation,
    type ItemCategory as ItemCategory,
    type ListAttribute as ListAttribute,
    type ListItemCategory as ListItemCategory,
    type ListProperty as ListProperty,
    type ItemCategoriesAPIListUnitGroupUnit as ListUnitGroupUnit,
    type ItemCategoriesAPIOwner as Owner,
    type ItemCategoriesAPIPageInfo as PageInfo,
    type Property as Property,
    type ItemCategoriesAPIUnit as Unit,
    type ItemCategoriesAPIUnitGroup as UnitGroup,
    type ItemCategoriesAPIUnitGroupUnit as UnitGroupUnit,
    type UpdateItemCategoryRequest as UpdateItemCategoryRequest,
    type ItemCategoryDeleteResponse as ItemCategoryDeleteResponse,
    type ItemCategoryChangeUnitGroupResponse as ItemCategoryChangeUnitGroupResponse,
    type ItemCategoryCreateParams as ItemCategoryCreateParams,
    type ItemCategoryRetrieveParams as ItemCategoryRetrieveParams,
    type ItemCategoryUpdateParams as ItemCategoryUpdateParams,
    type ItemCategoryListParams as ItemCategoryListParams,
    type ItemCategoryChangeUnitGroupParams as ItemCategoryChangeUnitGroupParams,
  };

  export {
    Materials as Materials,
    type MaterialsAPIAccount as Account,
    type MaterialsAPIAccountBranding as AccountBranding,
    type MaterialsAPIAccountPortal as AccountPortal,
    type MaterialsAPIAddress as Address,
    type MaterialsAPIAttribute as Attribute,
    type CreateMaterialRequest as CreateMaterialRequest,
    type MaterialsAPIGeolocation as Geolocation,
    type MaterialsAPIItem as Item,
    type MaterialsAPIItemCategory as ItemCategory,
    type MaterialsAPIListAttribute as ListAttribute,
    type ListMaterial as ListMaterial,
    type MaterialsAPIListProperty as ListProperty,
    type MaterialsAPIListUnitGroupUnit as ListUnitGroupUnit,
    type Material as Material,
    type MaterialsAPIOwner as Owner,
    type MaterialsAPIPageInfo as PageInfo,
    type MaterialsAPIProperty as Property,
    type Quantity as Quantity,
    type QuantityInputRequest as QuantityInputRequest,
    type MaterialsAPIRate as Rate,
    type RateInput as RateInput,
    type MaterialsAPIUnit as Unit,
    type MaterialsAPIUnitGroup as UnitGroup,
    type MaterialsAPIUnitGroupUnit as UnitGroupUnit,
    type UpdateMaterialRequest as UpdateMaterialRequest,
    type MaterialCreateParams as MaterialCreateParams,
    type MaterialRetrieveParams as MaterialRetrieveParams,
    type MaterialUpdateParams as MaterialUpdateParams,
    type MaterialListParams as MaterialListParams,
  };

  export {
    Parts as Parts,
    type PartsAPIAccount as Account,
    type PartsAPIAccountBranding as AccountBranding,
    type PartsAPIAccountPortal as AccountPortal,
    type PartsAPIAddress as Address,
    type PartsAPIAttribute as Attribute,
    type CreatePartRequest as CreatePartRequest,
    type PartsAPIGeolocation as Geolocation,
    type PartsAPIItem as Item,
    type PartsAPIItemCategory as ItemCategory,
    type PartsAPIListAttribute as ListAttribute,
    type ListPart as ListPart,
    type PartsAPIListProperty as ListProperty,
    type PartsAPIListUnitGroupUnit as ListUnitGroupUnit,
    type PartsAPIOwner as Owner,
    type PartsAPIPageInfo as PageInfo,
    type Part as Part,
    type PartsAPIProperty as Property,
    type PartsAPIRate as Rate,
    type PartsAPIRateInput as RateInput,
    type PartsAPIUnit as Unit,
    type PartsAPIUnitGroup as UnitGroup,
    type PartsAPIUnitGroupUnit as UnitGroupUnit,
    type UpdatePartRequest as UpdatePartRequest,
    type PartCreateParams as PartCreateParams,
    type PartRetrieveParams as PartRetrieveParams,
    type PartUpdateParams as PartUpdateParams,
    type PartListParams as PartListParams,
  };

  export {
    ProductLines as ProductLines,
    type Account as Account,
    type AccountBranding as AccountBranding,
    type AccountPortal as AccountPortal,
    type Address as Address,
    type CreateProductLineRequest as CreateProductLineRequest,
    type Geolocation as Geolocation,
    type ListProductLine as ListProductLine,
    type ListUnitGroupUnit as ListUnitGroupUnit,
    type Owner as Owner,
    type PageInfo as PageInfo,
    type ProductLine as ProductLine,
    type Unit as Unit,
    type UnitGroup as UnitGroup,
    type UnitGroupUnit as UnitGroupUnit,
    type UpdateProductLineRequest as UpdateProductLineRequest,
    type ProductLineDeleteResponse as ProductLineDeleteResponse,
    type ProductLineCreateParams as ProductLineCreateParams,
    type ProductLineRetrieveParams as ProductLineRetrieveParams,
    type ProductLineUpdateParams as ProductLineUpdateParams,
    type ProductLineListParams as ProductLineListParams,
  };

  export {
    Products as Products,
    type ProductsAPIAccount as Account,
    type ProductsAPIAccountBranding as AccountBranding,
    type ProductsAPIAccountPortal as AccountPortal,
    type ProductsAPIAddress as Address,
    type ProductsAPIAttribute as Attribute,
    type CreateProductRequest as CreateProductRequest,
    type ProductsAPIGeolocation as Geolocation,
    type ProductsAPIItem as Item,
    type ProductsAPIItemCategory as ItemCategory,
    type ProductsAPIListAttribute as ListAttribute,
    type ListProduct as ListProduct,
    type ProductsAPIListProperty as ListProperty,
    type ProductsAPIListUnitGroupUnit as ListUnitGroupUnit,
    type ProductsAPIOwner as Owner,
    type ProductsAPIPageInfo as PageInfo,
    type Product as Product,
    type ProductsAPIProductLine as ProductLine,
    type ProductsAPIProperty as Property,
    type ProductsAPIRate as Rate,
    type ProductsAPIRateInput as RateInput,
    type ProductsAPIUnit as Unit,
    type ProductsAPIUnitGroup as UnitGroup,
    type ProductsAPIUnitGroupUnit as UnitGroupUnit,
    type UpdateProductRequest as UpdateProductRequest,
    type ProductCreateParams as ProductCreateParams,
    type ProductRetrieveParams as ProductRetrieveParams,
    type ProductUpdateParams as ProductUpdateParams,
    type ProductListParams as ProductListParams,
    type ProductDeleteParams as ProductDeleteParams,
    type ProductChangeProductLineParams as ProductChangeProductLineParams,
  };

  export {
    ProductTypes as ProductTypes,
    type CreateProductTypeRequest as CreateProductTypeRequest,
    type ListProductType as ListProductType,
    type ProductTypesAPIPageInfo as PageInfo,
    type ProductType as ProductType,
    type UpdateProductTypeRequest as UpdateProductTypeRequest,
    type ProductTypeDeleteResponse as ProductTypeDeleteResponse,
    type ProductTypeCreateParams as ProductTypeCreateParams,
    type ProductTypeUpdateParams as ProductTypeUpdateParams,
    type ProductTypeListParams as ProductTypeListParams,
  };

  export { CatalogAPICatalog as Catalog };
}
