// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as ActionsAPI from './actions';
import {
  ActionCheckDuplicatesParams,
  ActionEmailRecordParams,
  ActionEmailRecordResponse,
  ActionRequestDemoParams,
  ActionSubmitFeedbackParams,
  Actions,
  CheckDuplicateRequest,
  CheckDuplicateResult,
  EmailRecordRequest,
  MessageResource,
  RequestDemoRequest,
  SubmitFeedbackRequest,
} from './actions';
import * as AnalyticsAPI from './analytics';
import {
  Account,
  AccountBranding,
  AccountPortal,
  Address,
  Analytics,
  AnalyticsItem,
  AnalyticsLot,
  AnalyticsRate,
  AnalyticsRetrieveWeeksOfSalesParams,
  AnalyticsUnitGroup,
  AnalyticsUnitGroupUnit,
  AnalyticsUpdateDeliveriesParams,
  AnalyticsUpdateDemandForecastParams,
  AnalyticsUpdateInventoryReceiptsParams,
  AnalyticsUpdateManufacturingBatchParams,
  AnalyticsUpdateManufacturingParams,
  AnalyticsUpdateMaterialsParams,
  AnalyticsUpdateNewCustomersParams,
  AnalyticsUpdateOeeParams,
  AnalyticsUpdateOpenBatchesParams,
  AnalyticsUpdateOrdersParams,
  AnalyticsUpdateProductionCostsParams,
  AnalyticsUpdateQuarterlyOrdersParams,
  AnalyticsUpdateSalesParams,
  AnalyzeDeliveriesRequest,
  AnalyzeDeliveriesResponse,
  AnalyzeDemandForecastRequest,
  AnalyzeDemandForecastResponse,
  AnalyzeInventoryReceiptsRequest,
  AnalyzeInventoryReceiptsResponse,
  AnalyzeManufacturingBatchRequest,
  AnalyzeManufacturingBatchResponse,
  AnalyzeManufacturingRequest,
  AnalyzeManufacturingResponse,
  AnalyzeMaterialsRequest,
  AnalyzeMaterialsResponse,
  AnalyzeNewCustomersRequest,
  AnalyzeNewCustomersResponse,
  AnalyzeOeeRequest,
  AnalyzeOeeResponse,
  AnalyzeOpenBatchesRequest,
  AnalyzeOpenBatchesResponse,
  AnalyzeOrdersRequest,
  AnalyzeOrdersResponse,
  AnalyzeProductionCostsRequest,
  AnalyzeProductionCostsResponse,
  AnalyzeQuarterlyOrdersRequest,
  AnalyzeQuarterlyOrdersResponse,
  AnalyzeSalesRequest,
  AnalyzeSalesResponse,
  AnalyzeWeeksOfSalesResponse,
  Attribute,
  ChartData,
  Consumption,
  Coordinate,
  CostBreakdown,
  DateTimeCoordinate,
  DeliveryChartData,
  DeliveryStatistics,
  DemandForecastForecastPoint,
  DemandForecastPoint,
  DemandForecastRow,
  Department,
  Entity,
  Geolocation,
  InventoryReceiptSummaryEntry,
  Item,
  ItemCategory,
  ListAttribute,
  ListConsumption,
  ListLocation,
  ListMachine,
  ListProductionStep,
  ListProperty,
  ListScanningStation,
  ListUnitGroupUnit,
  Location,
  Machine,
  ManufacturingMetrics,
  MaterialAnalyticsEntry,
  NewCustomersData,
  OeeDepartment,
  OpenBatchSummary,
  OrderEntry,
  Owner,
  PageInfo,
  ProductionCostItem,
  ProductionOutput,
  ProductionStep,
  Property,
  Quantity,
  Rate,
  RevenueForecastPoint,
  SalesEntry,
  ScanningStation,
  Unit,
  UnitGroup,
  UnitGroupUnit,
  WeeksOfSalesItem,
} from './analytics';
import * as AuditEventsAPI from './audit-events';
import {
  Account as AuditEventsAPIAccount,
  AccountBranding as AuditEventsAPIAccountBranding,
  AccountPortal as AuditEventsAPIAccountPortal,
  Actor,
  Address as AuditEventsAPIAddress,
  AuditEvent,
  AuditEventListParams,
  AuditEventRetrieveParams,
  AuditEvents,
  AuditFieldChange,
  Geolocation as AuditEventsAPIGeolocation,
  ListAuditEvent,
  ListAuditFieldChange,
  ListObjectType,
  Owner as AuditEventsAPIOwner,
  PageInfo as AuditEventsAPIPageInfo,
  RequestLog,
  Role,
} from './audit-events';
import * as EmailLogsAPI from './email-logs';
import {
  Account as EmailLogsAPIAccount,
  AccountBranding as EmailLogsAPIAccountBranding,
  AccountPortal as EmailLogsAPIAccountPortal,
  Actor as EmailLogsAPIActor,
  Address as EmailLogsAPIAddress,
  EmailLog,
  EmailLogListParams,
  EmailLogRetrieveParams,
  EmailLogs,
  Geolocation as EmailLogsAPIGeolocation,
  ListEmailLog,
  Owner as EmailLogsAPIOwner,
  PageInfo as EmailLogsAPIPageInfo,
  Role as EmailLogsAPIRole,
} from './email-logs';
import * as RequestLogsAPI from './request-logs';
import {
  Account as RequestLogsAPIAccount,
  AccountBranding as RequestLogsAPIAccountBranding,
  AccountPortal as RequestLogsAPIAccountPortal,
  Actor as RequestLogsAPIActor,
  Address as RequestLogsAPIAddress,
  Geolocation as RequestLogsAPIGeolocation,
  ListRequestLog,
  Owner as RequestLogsAPIOwner,
  PageInfo as RequestLogsAPIPageInfo,
  RequestLog as RequestLogsAPIRequestLog,
  RequestLogListParams,
  RequestLogRetrieveParams,
  RequestLogs,
  Role as RequestLogsAPIRole,
} from './request-logs';
import * as SandboxesAPI from './sandboxes';
import {
  Account as SandboxesAPIAccount,
  AccountBranding as SandboxesAPIAccountBranding,
  AccountPortal as SandboxesAPIAccountPortal,
  Address as SandboxesAPIAddress,
  CreateSandboxRequest,
  Geolocation as SandboxesAPIGeolocation,
  ListSandbox,
  PageInfo as SandboxesAPIPageInfo,
  Sandbox,
  SandboxCreateParams,
  SandboxDeleteResponse,
  SandboxListParams,
  SandboxRetrieveParams,
  Sandboxes,
} from './sandboxes';
import * as SysPropertiesAPI from './sys-properties';
import {
  ListSysProperty,
  PageInfo as SysPropertiesAPIPageInfo,
  SysProperties,
  SysProperty,
  SysPropertyListParams,
  SysPropertyType,
  SysPropertyUpdateParams,
  SysPropertyValue,
  UpdateSysPropertyRequest,
} from './sys-properties';
import * as AddressesAPI from './addresses/addresses';
import {
  AddressComponents,
  AddressDetailsResult,
  AddressRetrieveDetailsParams,
  AddressRetrieveSuggestionsParams,
  AddressSuggestion,
  Addresses,
  ListAddressSuggestion,
  PageInfo as AddressesAPIPageInfo,
} from './addresses/addresses';

export class Core extends APIResource {
  sandboxes: SandboxesAPI.Sandboxes = new SandboxesAPI.Sandboxes(this._client);
  requestLogs: RequestLogsAPI.RequestLogs = new RequestLogsAPI.RequestLogs(this._client);
  auditEvents: AuditEventsAPI.AuditEvents = new AuditEventsAPI.AuditEvents(this._client);
  sysProperties: SysPropertiesAPI.SysProperties = new SysPropertiesAPI.SysProperties(this._client);
  addresses: AddressesAPI.Addresses = new AddressesAPI.Addresses(this._client);
  emailLogs: EmailLogsAPI.EmailLogs = new EmailLogsAPI.EmailLogs(this._client);
  analytics: AnalyticsAPI.Analytics = new AnalyticsAPI.Analytics(this._client);
  actions: ActionsAPI.Actions = new ActionsAPI.Actions(this._client);
}

Core.Sandboxes = Sandboxes;
Core.RequestLogs = RequestLogs;
Core.AuditEvents = AuditEvents;
Core.SysProperties = SysProperties;
Core.Addresses = Addresses;
Core.EmailLogs = EmailLogs;
Core.Analytics = Analytics;
Core.Actions = Actions;

export declare namespace Core {
  export {
    Sandboxes as Sandboxes,
    type SandboxesAPIAccount as Account,
    type SandboxesAPIAccountBranding as AccountBranding,
    type SandboxesAPIAccountPortal as AccountPortal,
    type SandboxesAPIAddress as Address,
    type CreateSandboxRequest as CreateSandboxRequest,
    type SandboxesAPIGeolocation as Geolocation,
    type ListSandbox as ListSandbox,
    type SandboxesAPIPageInfo as PageInfo,
    type Sandbox as Sandbox,
    type SandboxDeleteResponse as SandboxDeleteResponse,
    type SandboxCreateParams as SandboxCreateParams,
    type SandboxRetrieveParams as SandboxRetrieveParams,
    type SandboxListParams as SandboxListParams,
  };

  export {
    RequestLogs as RequestLogs,
    type RequestLogsAPIAccount as Account,
    type RequestLogsAPIAccountBranding as AccountBranding,
    type RequestLogsAPIAccountPortal as AccountPortal,
    type RequestLogsAPIActor as Actor,
    type RequestLogsAPIAddress as Address,
    type RequestLogsAPIGeolocation as Geolocation,
    type ListRequestLog as ListRequestLog,
    type RequestLogsAPIOwner as Owner,
    type RequestLogsAPIPageInfo as PageInfo,
    type RequestLogsAPIRequestLog as RequestLog,
    type RequestLogsAPIRole as Role,
    type RequestLogRetrieveParams as RequestLogRetrieveParams,
    type RequestLogListParams as RequestLogListParams,
  };

  export {
    AuditEvents as AuditEvents,
    type AuditEventsAPIAccount as Account,
    type AuditEventsAPIAccountBranding as AccountBranding,
    type AuditEventsAPIAccountPortal as AccountPortal,
    type Actor as Actor,
    type AuditEventsAPIAddress as Address,
    type AuditEvent as AuditEvent,
    type AuditFieldChange as AuditFieldChange,
    type AuditEventsAPIGeolocation as Geolocation,
    type ListAuditEvent as ListAuditEvent,
    type ListAuditFieldChange as ListAuditFieldChange,
    type ListObjectType as ListObjectType,
    type AuditEventsAPIOwner as Owner,
    type AuditEventsAPIPageInfo as PageInfo,
    type RequestLog as RequestLog,
    type Role as Role,
    type AuditEventRetrieveParams as AuditEventRetrieveParams,
    type AuditEventListParams as AuditEventListParams,
  };

  export {
    SysProperties as SysProperties,
    type ListSysProperty as ListSysProperty,
    type SysPropertiesAPIPageInfo as PageInfo,
    type SysProperty as SysProperty,
    type SysPropertyType as SysPropertyType,
    type SysPropertyValue as SysPropertyValue,
    type UpdateSysPropertyRequest as UpdateSysPropertyRequest,
    type SysPropertyUpdateParams as SysPropertyUpdateParams,
    type SysPropertyListParams as SysPropertyListParams,
  };

  export {
    Addresses as Addresses,
    type AddressComponents as AddressComponents,
    type AddressDetailsResult as AddressDetailsResult,
    type AddressSuggestion as AddressSuggestion,
    type ListAddressSuggestion as ListAddressSuggestion,
    type AddressesAPIPageInfo as PageInfo,
    type AddressRetrieveDetailsParams as AddressRetrieveDetailsParams,
    type AddressRetrieveSuggestionsParams as AddressRetrieveSuggestionsParams,
  };

  export {
    EmailLogs as EmailLogs,
    type EmailLogsAPIAccount as Account,
    type EmailLogsAPIAccountBranding as AccountBranding,
    type EmailLogsAPIAccountPortal as AccountPortal,
    type EmailLogsAPIActor as Actor,
    type EmailLogsAPIAddress as Address,
    type EmailLog as EmailLog,
    type EmailLogsAPIGeolocation as Geolocation,
    type ListEmailLog as ListEmailLog,
    type EmailLogsAPIOwner as Owner,
    type EmailLogsAPIPageInfo as PageInfo,
    type EmailLogsAPIRole as Role,
    type EmailLogRetrieveParams as EmailLogRetrieveParams,
    type EmailLogListParams as EmailLogListParams,
  };

  export {
    Analytics as Analytics,
    type Account as Account,
    type AccountBranding as AccountBranding,
    type AccountPortal as AccountPortal,
    type Address as Address,
    type AnalyticsItem as AnalyticsItem,
    type AnalyticsLot as AnalyticsLot,
    type AnalyticsRate as AnalyticsRate,
    type AnalyticsUnitGroup as AnalyticsUnitGroup,
    type AnalyticsUnitGroupUnit as AnalyticsUnitGroupUnit,
    type AnalyzeDeliveriesRequest as AnalyzeDeliveriesRequest,
    type AnalyzeDeliveriesResponse as AnalyzeDeliveriesResponse,
    type AnalyzeDemandForecastRequest as AnalyzeDemandForecastRequest,
    type AnalyzeDemandForecastResponse as AnalyzeDemandForecastResponse,
    type AnalyzeInventoryReceiptsRequest as AnalyzeInventoryReceiptsRequest,
    type AnalyzeInventoryReceiptsResponse as AnalyzeInventoryReceiptsResponse,
    type AnalyzeManufacturingBatchRequest as AnalyzeManufacturingBatchRequest,
    type AnalyzeManufacturingBatchResponse as AnalyzeManufacturingBatchResponse,
    type AnalyzeManufacturingRequest as AnalyzeManufacturingRequest,
    type AnalyzeManufacturingResponse as AnalyzeManufacturingResponse,
    type AnalyzeMaterialsRequest as AnalyzeMaterialsRequest,
    type AnalyzeMaterialsResponse as AnalyzeMaterialsResponse,
    type AnalyzeNewCustomersRequest as AnalyzeNewCustomersRequest,
    type AnalyzeNewCustomersResponse as AnalyzeNewCustomersResponse,
    type AnalyzeOeeRequest as AnalyzeOeeRequest,
    type AnalyzeOeeResponse as AnalyzeOeeResponse,
    type AnalyzeOpenBatchesRequest as AnalyzeOpenBatchesRequest,
    type AnalyzeOpenBatchesResponse as AnalyzeOpenBatchesResponse,
    type AnalyzeOrdersRequest as AnalyzeOrdersRequest,
    type AnalyzeOrdersResponse as AnalyzeOrdersResponse,
    type AnalyzeProductionCostsRequest as AnalyzeProductionCostsRequest,
    type AnalyzeProductionCostsResponse as AnalyzeProductionCostsResponse,
    type AnalyzeQuarterlyOrdersRequest as AnalyzeQuarterlyOrdersRequest,
    type AnalyzeQuarterlyOrdersResponse as AnalyzeQuarterlyOrdersResponse,
    type AnalyzeSalesRequest as AnalyzeSalesRequest,
    type AnalyzeSalesResponse as AnalyzeSalesResponse,
    type AnalyzeWeeksOfSalesResponse as AnalyzeWeeksOfSalesResponse,
    type Attribute as Attribute,
    type ChartData as ChartData,
    type Consumption as Consumption,
    type Coordinate as Coordinate,
    type CostBreakdown as CostBreakdown,
    type DateTimeCoordinate as DateTimeCoordinate,
    type DeliveryChartData as DeliveryChartData,
    type DeliveryStatistics as DeliveryStatistics,
    type DemandForecastForecastPoint as DemandForecastForecastPoint,
    type DemandForecastPoint as DemandForecastPoint,
    type DemandForecastRow as DemandForecastRow,
    type Department as Department,
    type Entity as Entity,
    type Geolocation as Geolocation,
    type InventoryReceiptSummaryEntry as InventoryReceiptSummaryEntry,
    type Item as Item,
    type ItemCategory as ItemCategory,
    type ListAttribute as ListAttribute,
    type ListConsumption as ListConsumption,
    type ListLocation as ListLocation,
    type ListMachine as ListMachine,
    type ListProductionStep as ListProductionStep,
    type ListProperty as ListProperty,
    type ListScanningStation as ListScanningStation,
    type ListUnitGroupUnit as ListUnitGroupUnit,
    type Location as Location,
    type Machine as Machine,
    type ManufacturingMetrics as ManufacturingMetrics,
    type MaterialAnalyticsEntry as MaterialAnalyticsEntry,
    type NewCustomersData as NewCustomersData,
    type OeeDepartment as OeeDepartment,
    type OpenBatchSummary as OpenBatchSummary,
    type OrderEntry as OrderEntry,
    type Owner as Owner,
    type PageInfo as PageInfo,
    type ProductionCostItem as ProductionCostItem,
    type ProductionOutput as ProductionOutput,
    type ProductionStep as ProductionStep,
    type Property as Property,
    type Quantity as Quantity,
    type Rate as Rate,
    type RevenueForecastPoint as RevenueForecastPoint,
    type SalesEntry as SalesEntry,
    type ScanningStation as ScanningStation,
    type Unit as Unit,
    type UnitGroup as UnitGroup,
    type UnitGroupUnit as UnitGroupUnit,
    type WeeksOfSalesItem as WeeksOfSalesItem,
    type AnalyticsRetrieveWeeksOfSalesParams as AnalyticsRetrieveWeeksOfSalesParams,
    type AnalyticsUpdateDeliveriesParams as AnalyticsUpdateDeliveriesParams,
    type AnalyticsUpdateDemandForecastParams as AnalyticsUpdateDemandForecastParams,
    type AnalyticsUpdateInventoryReceiptsParams as AnalyticsUpdateInventoryReceiptsParams,
    type AnalyticsUpdateManufacturingParams as AnalyticsUpdateManufacturingParams,
    type AnalyticsUpdateManufacturingBatchParams as AnalyticsUpdateManufacturingBatchParams,
    type AnalyticsUpdateMaterialsParams as AnalyticsUpdateMaterialsParams,
    type AnalyticsUpdateNewCustomersParams as AnalyticsUpdateNewCustomersParams,
    type AnalyticsUpdateOeeParams as AnalyticsUpdateOeeParams,
    type AnalyticsUpdateOpenBatchesParams as AnalyticsUpdateOpenBatchesParams,
    type AnalyticsUpdateOrdersParams as AnalyticsUpdateOrdersParams,
    type AnalyticsUpdateProductionCostsParams as AnalyticsUpdateProductionCostsParams,
    type AnalyticsUpdateQuarterlyOrdersParams as AnalyticsUpdateQuarterlyOrdersParams,
    type AnalyticsUpdateSalesParams as AnalyticsUpdateSalesParams,
  };

  export {
    Actions as Actions,
    type CheckDuplicateRequest as CheckDuplicateRequest,
    type CheckDuplicateResult as CheckDuplicateResult,
    type EmailRecordRequest as EmailRecordRequest,
    type MessageResource as MessageResource,
    type RequestDemoRequest as RequestDemoRequest,
    type SubmitFeedbackRequest as SubmitFeedbackRequest,
    type ActionEmailRecordResponse as ActionEmailRecordResponse,
    type ActionCheckDuplicatesParams as ActionCheckDuplicatesParams,
    type ActionEmailRecordParams as ActionEmailRecordParams,
    type ActionRequestDemoParams as ActionRequestDemoParams,
    type ActionSubmitFeedbackParams as ActionSubmitFeedbackParams,
  };
}
